USE [master]
GO

/****** Object:  Database [blockchain]    Script Date: 11/15/2014 15:35:33 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'blockchain')
DROP DATABASE [blockchain]
GO

USE [master]
GO

/****** Object:  Database [blockchain]    Script Date: 11/15/2014 15:35:33 ******/
CREATE DATABASE [blockchain] ON  PRIMARY 
( NAME = N'blockchain', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\blockchain.mdf' , SIZE = 6378496KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'blockchain_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\blockchain_log.ldf' , SIZE = 136064KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [blockchain] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [blockchain].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [blockchain] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [blockchain] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [blockchain] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [blockchain] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [blockchain] SET ARITHABORT OFF 
GO

ALTER DATABASE [blockchain] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [blockchain] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [blockchain] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [blockchain] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [blockchain] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [blockchain] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [blockchain] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [blockchain] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [blockchain] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [blockchain] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [blockchain] SET  DISABLE_BROKER 
GO

ALTER DATABASE [blockchain] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [blockchain] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [blockchain] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [blockchain] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [blockchain] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [blockchain] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [blockchain] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [blockchain] SET  READ_WRITE 
GO

ALTER DATABASE [blockchain] SET RECOVERY FULL 
GO

ALTER DATABASE [blockchain] SET  MULTI_USER 
GO

ALTER DATABASE [blockchain] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [blockchain] SET DB_CHAINING OFF 
GO


